### ISSUE TITLE
Zero size cache file breaks load_cache

### ISSUE THREAD

**Issue by austinmroczek** [MisterWil/skybellpy#9]
I'm running skybellpy via the skybell component of Home Assistant.  Somehow I ended up with a skybell_cache.pickle file with zero bytes.  When skybellpy tries _load_cache() it gives the following error:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/setup.py", line 154, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/skybell/__init__.py", line 44, in setup
    get_devices=True, cache_path=cache)
  File "/srv/homeassistant/lib/python3.5/site-packages/skybellpy/__init__.py", line 58, in __init__
    self._load_cache()
  File "/srv/homeassistant/lib/python3.5/site-packages/skybellpy/__init__.py", line 233, in _load_cache
    loaded_cache = UTILS.load_cache(self._cache_path)
  File "/srv/homeassistant/lib/python3.5/site-packages/skybellpy/utils.py", line 17, in load_cache
    return pickle.load(handle)
EOFError: Ran out of input

Deleting the zero size file solves the problem.

**Comment by MisterWil** [comment]
Fixed with release PR #10 in release 0.4.0
